const Actions = {
    Registration:{
        REG_USER_NAME_CHANGE: 'REG_USER_NAME_CHANGE',
        TOGGLE_ERROR_TOAST: 'TOGGLE_ERROR_TOAST'
    },
    Dashboard:{
        UPDATE_CURRENT_LOGIN_NAME:'UPDATE_CURRENT_LOGIN_NAME',
        UPDATE_TO_USER_SELECTION:'UPDATE_TO_USER_SELECTION',
        MESSAGE_ENTRY_CHANGE:'MESSAGE_ENTRY_CHANGE',
        UPDATE_MESSAGES_LIST:'UPDATE_MESSAGES_LIST',
        TOGGLE_ERROR_TOAST:'TOGGLE_ERROR_TOAST',
        UPDATE_ONLINE_USERS:'UPDATE_ONLINE_USERS'
    }  
};

export default Actions;
